//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetTeam_Prj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.like_count = "0";
            this.img_path = "default.jpg";
            this.Comments = new HashSet<Comment>();
            this.Transactions = new HashSet<Transaction>();
            this.likes = new HashSet<like>();
        }
    
        public int item_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> listing_price { get; set; }
        public string description { get; set; }
        public Nullable<int> category { get; set; }
        public string like_count { get; set; }
        public string img_path { get; set; }
        public HttpPostedFileBase img_file { get; set; }

        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
    }
}
