//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetTeam_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int trans_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
